M48
; DRILL file {KiCad 9.0.8-9.0.8~ubuntu22.04.1} date 2026-04-02T10:10:10+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-04-02T10:10:10+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8-9.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1575
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1693
%
G90
G05
T1
X9.0827Y-1.9823
X9.0827Y-6.9035
T2
X5.1427Y-1.9833
X5.1427Y-6.9055
M30
